language: go

sudo: required

services:
  - docker

addons:
  apt:
    update: true

matrix:
  # fail fast
  fast_finish: true
  include:
    - go: 1.11.5

before_install:
  # coveralls.io deps
  - go get golang.org/x/tools/cmd/cover github.com/mattn/goveralls

install:
  - skip

script:
  - make ci
  - goveralls -coverprofile=target/.coverprofile -service=travis-ci -repotoken $COVERALLS_API_TOKEN

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: docker push docker.io/digitalocean/metis:$(git describe --tags)
  on:
    branch: master
